### ISSUE TITLE
helidon-codegen-api-stability triggers invalid record canonical constructor errors on JDK 26

### ISSUE THREAD

**Issue by jvissers** [helidon-io/helidon#12132]
## Environment Details
* Helidon Version: 4.5.0
* Helidon SE or Helidon MP: N/A for the minimal reproducer; originally observed in a Helidon SE application when using `io.helidon.bundles:helidon-bundles-apt:4.5.0`.
* JDK version: Java 26, Oracle build `26+35-2893`
* OS: Linux `5.14.0-687.5.3.el9_8.x86_64` (`amd64`)

----------

## Problem Description

`io.helidon.codegen:helidon-codegen-api-stability:4.5.0` can make valid Java record source fail compilation on JDK 26 with a misleading javac error:

```text
invalid canonical constructor in record Repro
  (canonical constructor must not contain explicit constructor invocation)
```

The record canonical constructor does not contain an explicit constructor invocation. It compiles successfully when the API stability processor is not run.

This is reproducible with a minimal Maven project that uses only `helidon-codegen-api-stability` as an annotation processor. It was originally observed after upgrading a project from Helidon 4.4.1 to 4.5.0 because `helidon-codegen-api-stability` was added to `helidon-bundles-apt` in 4.5.0 and is auto-discovered by javac.

Minimal source:

```java
package example;

record Repro(String name) {
    Repro {
        name = name.trim();
    }
}
```

Failure output:

```text
[ERROR] COMPILATION ERROR :
[ERROR] .../src/main/java/example/Repro.java:[4,5] invalid canonical constructor in record Repro
[ERROR]   (canonical constructor must not contain explicit constructor invocation)
```

Expected behavior:

* The source should compile.
* The API stability processor should only report Helidon API stability diagnostics, not cause unrelated record canonical constructor errors.
* `-Ahelidon.api=ignore` should ideally avoid API stability scanning side effects, but currently the processor still scans before deciding not to report diagnostics.

Additional investigation:

The likely trigger is in `ApiStabilityScanner`, which resolves expression nodes using `Trees.getElement(path)`:

```java
@Override
public Void visitIdentifier(IdentifierTree node, Void unused) {
    var path = trees.getPath(unit, node);
    return visit(path, () -> super.visitIdentifier(node, unused));
}

private Void visit(TreePath path, Supplier<Void> superCall) {
    if (path != null) {
        var elt = trees.getElement(path);
```

A small isolated processor test showed:

* `Trees.getPath(...)` on these nodes: passes
* `Trees.getTypeMirror(...)` on these nodes: passes
* `Trees.getElement(...)` on identifiers/member-selects/new-class expressions inside a record canonical constructor body: triggers the javac error
* normal classes and non-canonical record constructors: pass

So the processor appears to hit a JDK 26/javac interaction by resolving expression trees in record canonical constructors.

## Steps to reproduce

A minimal reproducer is attached in this issue as `bug-report/reproducer`.

1. Use JDK 26.
2. Run:

   ```bash
   cd bug-report/reproducer
   mvn clean compile
   ```

3. The compile fails with:

   ```text
   invalid canonical constructor in record Repro
     (canonical constructor must not contain explicit constructor invocation)
   ```

4. Disable annotation processing and the same Java source compiles:

   ```bash
   mvn clean compile -Dmaven.compiler.proc=none
   ```

5. Suppressing Helidon API diagnostics does not avoid the failure because scanning still happens:

   ```bash
   mvn clean compile -Dmaven.compiler.compilerArgs=-Ahelidon.api=ignore
   ```

Potential fixes to consider:

* Remove `helidon-codegen-api-stability` from the default `helidon-bundles-apt` bundle, or
* skip this processor's source scan entirely when all API stability checks are configured as `ignore`, or
* avoid `Trees.getElement(...)` for expression nodes inside record canonical constructors on JDK 26, or otherwise guard that path.

[helidon-api-stability-record-reproducer.zip](https://github.com/user-attachments/files/29284772/helidon-api-stability-record-reproducer.zip)
